#!/bin/bash

if [ -z "$PHOTOBASE" ]; then
	echo "missing PHOTOBASE setting" >&2
	exit 1
fi

if [ -z "$INTERVAL" ]; then
	echo "missing INTERVAL setting" >&2
	exit 1
fi

TODAY=$(date +%Y-%m-%d)
PHOTOS=$PHOTOBASE/$TODAY

mkdir -p $PHOTOS
/usr/bin/raspistill -o $PHOTOS/photo-%d.jpg -tl $INTERVAL
