#!/bin/bash

if [ -z "$PHOTOBASE" ]; then
	echo "missing PHOTOBASE setting" >&2
	exit 1
fi

if [ -z "$INTERVAL" ]; then
	echo "missing INTERVAL setting" >&2
	exit 1
fi

TODAY=$(date +%Y-%m-%d)
PHOTOS=$PHOTOBASE/$TODAY

mkdir -p $PHOTOS

# raspistill won't take the first photo until after $INTERVAL has elapsed
/usr/bin/raspistill -o $PHOTOS/photo-$(date +%Y%m%dT%H%M%S)-0000.jpg
/usr/bin/raspistill -o $PHOTOS/photo-$(date +%Y%m%dT%H%M%S)-1%03d.jpg -t 0 -tl $INTERVAL
